### ISSUE TITLE
Issue with joining lobbies.

### ISSUE THREAD

**Issue by 3749xelA** [legoandmars/GorillaCosmetics#12]
It's probably been mentioned here already, but I just think it's appropriate to mention it.

While using GorillaCosmetics, you can only join 1 lobby per session of Gorilla Tag. As soon as you leave a lobby and try to join a new one, the game will instantly crash. While not being the biggest problem ever, it's just pretty annoying to have to restart the game every time you try to join a new lobby.

quick edit: this happens on quest, but I don't know about PC, this might be in the wrong thing.

**Comment by In4init3** [comment]
on pc the mod straight doesn't load the cosmetics
